version: '2'
services:
  activemq:
    image: rmohr/activemq:5.10.0
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
  mongo:
    image: mongo:3.2.8
    ports:
      - "27017:27017"
  cassandra:
    image: cassandra:3.7
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
  zookeeper:
#    image: jplock/zookeeper:3.4.8
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

#  kafka:
#    image: wurstmeister/kafka:0.8.2.0
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
##      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.40.104
#      KAFKA_CREATE_TOPICS: "gdelt:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
